---
title: "Pepsi Cola Project"
author: "James"
date: "2025-02-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Introduction

The original dataset contained information for both Coca-Cola (Brand 1) and Pepsi-Cola (Brand 2) in a single sheet. For better clarity and ease of analysis, the data was restructured into two separate sheets named `brand1` and `brand2`. Both sheets contain the same columns, with each column representing the respective brand's data. This restructuring allows for a more focused analysis of Pepsi-Cola's sales drivers, which is the primary objective of this project.

### Question 1
Calculate descriptive (summary) statistics about the sales and use of marketing mix variables for both brands. Who is the market leader? How do the brands compare in terms of pricing, promotion, assortment? How do the brands compare in terms of allocation of spending between the four advertising instruments? Report the statistics and discuss your learnings and insights.


